### ISSUE TITLE
Set checksums with Jinja (reuse in `source` section)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cuda-feedstock#67]
Currently some of the tooling that conda-forge uses has trouble with syntax like this

```yaml
...

  sha256: ec682bac6387f9cdfd0c20b25a16cd6ed0b8b3b7ff42be9eaeb41828e3a72572  # [linux64]
  sha256: 84668dcb2159f9efd912a66ed5afe5d6533b72a81bbabc98b26ac7ac7a36105a  # [aarch64]
  sha256: 1a87ec80f8c0e5a39badc87010d479930c5b63abd788b3a05bd688a5980a3d07  # [win]

...
```

A simple way to fix this would be to do something like the following

```yaml
{% set sha256 = "ec682bac6387f9cdfd0c20b25a16cd6ed0b8b3b7ff42be9eaeb41828e3a72572" %}  # [linux64]
{% set sha256 =   sha256: 84668dcb2159f9efd912a66ed5afe5d6533b72a81bbabc98b26ac7ac7a36105a" %}  # [aarch64]
{% set sha256 =   sha256: 1a87ec80f8c0e5a39badc87010d479930c5b63abd788b3a05bd688a5980a3d07" %}  # [win]

...

  sha256: {{ sha256 }}
```

We could in turn put those Jinja `set` lines near version information, which we often will change together. This may simplify diffs and make it easier to confirm all the expected content was changed
