### ISSUE TITLE
Use `cuda_compiler` to filter out old & new CUDA stack differences

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cuda-feedstock#73]
To simplify checks and clarify the differences between the old and new CUDA stacks, we should use `cuda_compiler` in selectors and Jinja.

For example this is what handling `cudatoolkit` and `cuda-cudart` would look like

```yaml
...

requirements:
  ...
  run:
    ...
    - cudatoolkit    # [cuda_compiler == "nvcc"]
    - cuda-cudart    # [cuda_compiler == "cuda-nvcc"]

...
```

This isn't so much an issue for the CUDA Toolkit itself, which uses the new compiler stack exclusively. However it is an issue for other NVIDIA and third-party packages
